# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 127fe376aaeee2fb16c27ab100a6ef7e8eabf383775283e5c2fb4f1497ca96c5bca13f876222dbff5646ccf80881d874d72e49d4af6a35d0cb94cbdc8871e88e

test:
  secret_key_base: 3ed19620a77fff6b905e928b2f2be2af942b666c4313fd69bc3a88b9b8925d798a9fd60bc88dd5302bfe2b276ab9daa57f644721d68a6318ddd789e8fa90cd3d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
